language: elixir

cache:
  directories:
  - priv/plts

elixir:
  - 1.6.5

otp_release:
  - 20.3

services:
  - postgresql

before_script:
  - epmd -daemon
  - MIX_ENV=test mix event_store.setup
  - MIX_ENV=jsonb mix event_store.setup

script:
  - mix test.all
  - mix dialyzer --halt-exit-status

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
